### ISSUE TITLE
Bug - Uploading files twice seems to overwrite the previous file.

### ISSUE THREAD

**Issue by OUeasley** [farhodius/sample-rest-api#3]
If we upload a file like sample.tgz and then upload sample.tgz again. The second sample.tgz will override the first one. Is it possible we can get the second one to have a number appended to it for example sample(1).tgz

**Comment by farhodius** [comment]
Hey Bryce! Thanks for the feedback. I'll take a look and fix asap.

**Comment by farhodius** [comment]
Added logic to prevent overriding of existing files.
